import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CardDeck(props) {
  const { nodes, materials } = useGLTF("/models/cardDeck/scene.gltf");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1.12, 1, 0.49]}
            position={[0, 0, 1]}
          >
            <mesh
              geometry={nodes["Ace_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ace_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ace_of_Clubs_27_0.geometry}
              material={materials.material_41}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ace_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ace_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ace_of_Diamonds_13_0.geometry}
              material={materials.material_28}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ace_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ace_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ace_of_Hearts_1_0.geometry}
              material={materials.material}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ace_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ace_of_Spades_02_-_Default_0"].geometry}
              material={materials["02_-_Default"]}
            />
            <mesh
              geometry={nodes["Ace_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Eigh_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Eigh_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Eigh_of_Hearts_8_0.geometry}
              material={materials.material_16}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Eight_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Eight_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Eight_of_Clubs_34_0.geometry}
              material={materials.material_42}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Eight_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Eight_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Eight_of_Diamonds_22_0.geometry}
              material={materials.material_29}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Eight_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Eight_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Eight_of_Spades_19_-_Default_0"].geometry}
              material={materials["19_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Five_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Five_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Five_of_Clubs_31_0.geometry}
              material={materials.material_43}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Five_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Five_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Five_of_Diamonds_18_0.geometry}
              material={materials.material_30}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Five_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Five_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Five_of_Hearts_5_0.geometry}
              material={materials.material_17}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Five_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Five_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Five_of_Spades_13_-_Default_0"].geometry}
              material={materials["13_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Four_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Four_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Four_of_Clubs_30_0.geometry}
              material={materials.material_44}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Four_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Four_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Four_of_Diamonds_17_0.geometry}
              material={materials.material_31}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Four_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Four_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Four_of_Hearts_4_0.geometry}
              material={materials.material_18}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Four_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Four_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Four_of_Spades_09_-_Default_0"].geometry}
              material={materials["09_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Jack_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Jack_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Jack_of_Clubs_37_0.geometry}
              material={materials.material_45}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Jack_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Jack_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Jack_of_Diamonds_25_0.geometry}
              material={materials.material_32}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Jack_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Jack_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Jack_of_Hearts_11_0.geometry}
              material={materials.material_19}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Jack_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Jack_of_Spades_04_-_Default_0"].geometry}
              material={materials["04_-_Default"]}
            />
            <mesh
              geometry={nodes["Jack_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["King_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.King_of_Clubs_43_0.geometry}
              material={materials.material_46}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["King_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Diamonds_22_-_Default_0"].geometry}
              material={materials["22_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["King_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.King_of_Hearts_14_0.geometry}
              material={materials.material_20}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["King_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Spades_06_-_Default_0"].geometry}
              material={materials["06_-_Default"]}
            />
            <mesh
              geometry={nodes["King_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Nine_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Nine_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Nine_of_Clubs_35_0.geometry}
              material={materials.material_47}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Nine_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Nine_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Nine_of_Diamonds_23_0.geometry}
              material={materials.material_34}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Nine_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Nine_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Nine_of_Hearts_9_0.geometry}
              material={materials.material_21}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Nine_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Nine_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Nine_of_Spades_20_-_Default_0"].geometry}
              material={materials["20_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Queen_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Queen_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Queen_of_Clubs_39_0.geometry}
              material={materials.material_48}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Queen_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Queen_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Queen_of_Diamonds_26_0.geometry}
              material={materials.material_35}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Queen_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Queen_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Queen_of_Hearts_12_0.geometry}
              material={materials.material_22}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Queen_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Queen_of_Spades_05_-_Default_0"].geometry}
              material={materials["05_-_Default"]}
            />
            <mesh
              geometry={nodes["Queen_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Seven_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Seven_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Seven_of_Clubs_33_0.geometry}
              material={materials.material_49}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Seven_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Seven_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Seven_of_Diamonds_21_0.geometry}
              material={materials.material_36}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Seven_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Seven_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Seven_of_Hearts_7_0.geometry}
              material={materials.material_23}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Seven_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Seven_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Seven_of_Spades_15_-_Default_0"].geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Six_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Six_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Six_of_Clubs_32_0.geometry}
              material={materials.material_50}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Six_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Six_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Six_of_Diamonds_20_0.geometry}
              material={materials.material_37}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Six_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Six_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Six_of_Hearts_6_0.geometry}
              material={materials.material_24}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Six_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Six_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Six_of_Spades_14_-_Default_0"].geometry}
              material={materials["14_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ten_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ten_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ten_of_Clubs_36_0.geometry}
              material={materials.material_51}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ten_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ten_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ten_of_Diamonds_24_0.geometry}
              material={materials.material_38}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ten_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ten_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Ten_of_Hearts_10_0.geometry}
              material={materials.material_25}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Ten_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Ten_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Ten_of_Spades_21_-_Default_0"].geometry}
              material={materials["21_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Three_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Three_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Three_of_Clubs_29_0.geometry}
              material={materials.material_52}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Three_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Three_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Three_of_Diamonds_16_0.geometry}
              material={materials.material_39}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Three_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Three_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Three_of_Hearts_3_0.geometry}
              material={materials.material_26}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Three_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Three_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes["Three_of_Spades_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Two_of_Clubs_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Two_of_Clubs_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Two_of_Clubs_28_0.geometry}
              material={materials.material_53}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Two_of_Diamonds_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Two_of_Diamonds_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Two_of_Diamonds_15_0.geometry}
              material={materials.material_40}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Two_of_Hearts_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Two_of_Hearts_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
            <mesh
              geometry={nodes.Two_of_Hearts_2_0.geometry}
              material={materials.material_27}
            />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={[1.12, 1, 0.49]}>
            <mesh
              geometry={nodes["Two_of_Spades_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh
              geometry={nodes["Two_of_Spades_03_-_Default_0"].geometry}
              material={materials["03_-_Default"]}
            />
            <mesh
              geometry={nodes["Two_of_Spades_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cardDeck/scene.gltf");
